(function(){POLARIS.dialog.add("pageoutline",function(h){function p(a,c,b){return function(){var e=this.getValue().trim(),e=!!(POLARIS.dialog.validate.number()(e)&&e>=c&&e<b+1);e||(alert(a),this.select());return e}}function n(){return function(){var a;a="1"==this.getDialog().getContentElement("info","radioOrientation").getValue()?parseFloat(this.getDialog().getContentElement("info","txtPaperWidth").getValue()):parseFloat(this.getDialog().getContentElement("info","txtPaperHeight").getValue());var c=
this.getValue().trim(),c=!!(POLARIS.dialog.validate.number()(c)&&0<=c&&c<a+1);if(!c)return alert(b.outline.invalidSize),this.select(),c;var c=parseFloat(this.getDialog().getContentElement("info","txtPaddingTop").getValue()),m=parseFloat(this.getDialog().getContentElement("info","txtPaddingBottom").getValue()),e=parseFloat(this.getDialog().getContentElement("info","txtHeaderHeight").getValue());if(0<e&&8>e){var d;d="\x3ctable\x3e\x3cthead\x3e\x3ctr\x3e";d+="\x3cth colspan\x3d3\x3e"+b.headerAndFooter.invalidHeaderHeight+
"\x3cbr\x3e\x3cbr\x3e\x3c/th\x3e";d+="\x3c/tr\x3e";d+="\x3c/thead\x3e";d+="\x3c/table\x3e";d=new POLARIS.plugins.notification(h,{message:d,type:"info",duration:3E3,width:300,valign:"top",align:"center"});d.show();e=8;this.getDialog().getContentElement("info","txtHeaderHeight").setValue(8)}d=parseFloat(this.getDialog().getContentElement("info","txtFooterHeight").getValue());0<d&&8>d&&(d="\x3ctable\x3e\x3cthead\x3e",d+="\x3ctr\x3e",d+="\x3cth colspan\x3d3\x3e"+b.headerAndFooter.invalidFooterHeight+
"\x3cbr\x3e\x3cbr\x3e\x3c/th\x3e",d+="\x3c/tr\x3e",d+="\x3c/thead\x3e",d+="\x3c/table\x3e",d=new POLARIS.plugins.notification(h,{message:d,type:"info",duration:3E3,width:300,valign:"top",align:"center"}),d.show(),d=8,this.getDialog().getContentElement("info","txtFooterHeight").setValue(8));NaN==c&&(c=0);NaN==m&&(m=0);NaN==e&&(e=0);NaN==d&&(d=0);(c=a>c+m+e+d)||alert(b.outline.invalidMargin);return c}}function q(){return function(){var a;a="1"==this.getDialog().getContentElement("info","radioOrientation").getValue()?
parseFloat(this.getDialog().getContentElement("info","txtPaperHeight").getValue()):parseFloat(this.getDialog().getContentElement("info","txtPaperWidth").getValue());var c=this.getValue().trim(),c=!!(POLARIS.dialog.validate.number()(c)&&0<=c&&c<a+1);if(!c)return alert(b.outline.invalidSize),this.select(),c;var c=parseFloat(this.getDialog().getContentElement("info","txtPaddingLeft").getValue()),m=parseFloat(this.getDialog().getContentElement("info","txtPaddingRight").getValue());NaN==c&&(c=0);NaN==
m&&(m=0);(c=a>c+m)||alert(b.outline.invalidMargin);return c}}var b=h.lang.pagination,l=function(a,c,m,e){this.isDefault=e;this.name=a;this.width=c;this.height=m;this.toString=function(){return a+" [ "+c+" x "+m+" "+b.outline.pageUnit+" ]"}},g={};g.Letter=new l("Letter",215.9,279.4);g.B5=new l("B5",182,257);g.B4=new l("B4",257,364);g.A4=new l("A4",210,297,!0);g.A3=new l("A3",297,420);var l=function(a){return POLARIS.tools.getNextId()+"_"+a},r=l("previewPagePanel"),t=l("previewPageBodyPanel"),u=l("previewHeaderPanel"),
v=l("previewFooterPanel"),f=function(a){var c,b;"1"==a.getContentElement("info","radioOrientation").getValue()?(c=a.getContentElement("info","txtPaperHeight").getValue(),b=a.getContentElement("info","txtPaperWidth").getValue()):(c=a.getContentElement("info","txtPaperWidth").getValue(),b=a.getContentElement("info","txtPaperHeight").getValue());c=parseInt(c);b=parseInt(b);var e=70,d=100,f=1;0!=c&&0!=b&&NaN!=c&&NaN!=b&&(c>b?(e=90,d=Math.round(90*b/c),f=Math.round(c/90)):(e=Math.round(90*c/b),d=90,f=
Math.round(b/90)));var k=POLARIS.document.getById(r);k&&(k.setStyle("width",e+"px"),k.setStyle("height",d+"px"));c=Math.round(a.getContentElement("info","txtPaddingLeft").getValue()/f);NaN==c&&(c=0,a.getContentElement("info","txtPaddingLeft").setValue("0"));k=Math.round(a.getContentElement("info","txtPaddingTop").getValue()/f);NaN==k&&(k=0);b=Math.round(a.getContentElement("info","txtPaddingRight").getValue()/f);NaN==b&&(b=0);var g=Math.round(a.getContentElement("info","txtPaddingBottom").getValue()/
f);NaN==g&&(g=0);var h=Math.round(a.getContentElement("info","txtHeaderHeight").getValue()/f);NaN==h&&(h=0);a=Math.round(a.getContentElement("info","txtFooterHeight").getValue()/f);NaN==a&&(a=0);e=e-c-b;NaN==e&&(e=0);0>e&&(e=0);d=d-k-g-h-a;NaN==d&&(d=0);0>d&&(d=0);if(f=POLARIS.document.getById(u))f.setStyle("width",e+"px"),f.setStyle("height",h+"px"),f.setStyle("margin-top",k+"px"),f.setStyle("margin-left",c+"px"),f.setStyle("margin-right",b+"px");if(k=POLARIS.document.getById(t))k.setStyle("width",
e+"px"),k.setStyle("height",d+"px"),k.setStyle("margin-left",c+"px"),k.setStyle("margin-right",b+"px");if(d=POLARIS.document.getById(v))d.setStyle("width",e+"px"),d.setStyle("height",a+"px"),d.setStyle("margin-bottom",g+"px"),d.setStyle("margin-left",c+"px"),d.setStyle("margin-right",b+"px")};return{title:b.outline.title,minWidth:460,minHeight:36,resizable:POLARIS.DIALOG_RESIZE_NONE,contents:[{id:"info",label:h.lang.common.generalTab,elements:[{type:"hbox",children:[{type:"vbox",children:[{type:"select",
id:"paperType",label:b.outline.pageSize,items:[],setup:function(a){this.clear();var c=parseFloat(a.width);a=parseFloat(a.height);var f=!1,e;for(e in g)this.add(g[e].toString(),e),c==g[e].width&&a==g[e].height&&(this.setValue(e),f=!0);this.add(b.outline.userPageSize,"0");f||this.setValue("0")},onChange:function(){g[this.getValue()]&&(this.getDialog().getContentElement("info","txtPaperWidth").setValue(g[this.getValue()].width),this.getDialog().getContentElement("info","txtPaperHeight").setValue(g[this.getValue()].height));
"0"==this.getValue()?(this.getDialog().getContentElement("info","txtPaperWidth").getInputElement().removeAttribute("readOnly"),this.getDialog().getContentElement("info","txtPaperHeight").getInputElement().removeAttribute("readOnly"),this.getDialog().getContentElement("info","txtPaperWidth").focus()):(this.getDialog().getContentElement("info","txtPaperWidth").getInputElement().setAttribute("readOnly",!0),this.getDialog().getContentElement("info","txtPaperHeight").getInputElement().setAttribute("readOnly",
!0))}},{type:"hbox",children:[{type:"hbox",children:[{type:"text",id:"txtPaperWidth",validate:p(b.outline.invalidWidth,1,1E3),label:b.outline.width,setup:function(a){this.setValue(parseFloat(a.width)+"")},onChange:function(){f(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]},{type:"hbox",children:[{type:"text",id:"txtPaperHeight",validate:p(b.outline.invalidHeight,1,1E3),label:b.outline.height,setup:function(a){this.setValue(parseFloat(a.height)+
"")},onChange:function(){f(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]}]},{type:"radio",id:"radioOrientation",label:b.outline.orientation,"default":"0",items:[[b.outline.landscape,"1"],[b.outline.portrait,"0"]],setup:function(a){this.setValue("portrait"==a.orientation?"0":"1")},onClick:function(){f(this.getDialog())},onChange:function(){f(this.getDialog())}}]},{type:"vbox",children:[{type:"html",html:"\x3cp\x3e"+b.outline.margin+
"\x3c/p\x3e"},{type:"vbox",style:"border: 1px solid #a0a2ab; border-radius: 2px; background-color: #fffeff; padding: 5px; height: 280px;",textalign:"center",children:[{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"html",html:""},{type:"hbox",children:[{type:"text",id:"txtPaddingTop",validate:n(),label:b.outline.marginTop,setup:function(a){this.setValue(parseInt(a.marginTop)+"")},onKeyUp:function(){f(this.getDialog())},onChange:function(){f(this.getDialog())}},
{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]},{type:"html",html:""}]},{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"html",html:""},{type:"hbox",children:[{type:"text",id:"txtHeaderHeight",validate:n(),label:b.outline.header,setup:function(a){this.setValue(parseInt(a.pageHeader.height)+"")},onKeyUp:function(){f(this.getDialog())},onChange:function(){f(this.getDialog())}},{type:"vbox",children:[{type:"html",
html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]},{type:"html",html:""}]},{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%","33%","33%"],children:[{type:"hbox",children:[{type:"text",id:"txtPaddingLeft",validate:q(),label:b.outline.marginLeft,setup:function(a){this.setValue(parseInt(a.marginLeft)+"")},onKeyUp:function(){f(this.getDialog())},onChange:function(){f(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]},
{type:"html",id:"pageOutlinePreview",html:'\x3cdiv style\x3d"border: 1px solid #a0a2ab;background-color:#fffeff;padding:0;width:100px;height:100px;line-height:100px;vertical-align:middle;text-align:center;overflow:hidden;"\x3e\x3cdiv id\x3d"'+r+'" style\x3d"border: 1px solid #a0a2ab;display:inline-block;overflow:hidden;"\x3e\x3cdiv id\x3d"'+u+'" style\x3d"background-color:#d2d2d2;display:block;width:auto;height:auto"\x3e\x3c/div\x3e\x3cdiv id\x3d"'+t+'" style\x3d"background-color:#f5f5f5;display:block;width:auto;height:auto"\x3e\x3c/div\x3e\x3cdiv id\x3d"'+
v+'" style\x3d"background-color:#d2d2d2;display:block;width:auto;height:auto"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e',setup:function(){}},{type:"hbox",children:[{type:"text",id:"txtPaddingRight",validate:q(),label:b.outline.marginRight,setup:function(a){this.setValue(parseInt(a.marginRight)+"")},onKeyUp:function(){f(this.getDialog())},onChange:function(){f(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]}]},{type:"hbox",verticalalign:"middle",
textalign:"center",widths:["33%","33%","33%"],children:[{type:"html",html:""},{type:"hbox",children:[{type:"text",id:"txtFooterHeight",validate:n(),label:b.outline.footer,setup:function(a){this.setValue(parseInt(a.pageFooter.height)+"")},onKeyUp:function(){f(this.getDialog())},onChange:function(){f(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]},{type:"html",html:""}]},{type:"hbox",verticalalign:"middle",textalign:"center",widths:["33%",
"33%","33%"],children:[{type:"html",html:""},{type:"hbox",children:[{type:"text",id:"txtPaddingBottom",validate:n(),label:b.outline.marginBottom,setup:function(a){this.setValue(parseInt(a.marginBottom)+"")},onKeyUp:function(){f(this.getDialog())},onChange:function(){f(this.getDialog())}},{type:"vbox",children:[{type:"html",html:"\x26nbsp;"},{type:"html",html:b.outline.pageUnit}]}]},{type:"html",html:""}]}]}]}]}]}],onLoad:function(){},onShow:function(){this.setupContent(h.plugins.pagination.pageInfo)},
onOk:function(){var a=h.plugins.pagination.pageInfo,c="0"==this.getContentElement("info","radioOrientation").getValue()?"portrait":"landscape",f=this.getContentElement("info","txtPaperWidth").getValue()+b.outline.pageUnit,e=this.getContentElement("info","txtPaperHeight").getValue()+b.outline.pageUnit,d=this.getContentElement("info","txtPaddingLeft").getValue()+b.outline.pageUnit,g=this.getContentElement("info","txtPaddingRight").getValue()+b.outline.pageUnit,k=this.getContentElement("info","txtPaddingTop").getValue()+
b.outline.pageUnit,l=this.getContentElement("info","txtPaddingBottom").getValue()+b.outline.pageUnit,n=this.getContentElement("info","txtHeaderHeight").getValue()+b.outline.pageUnit,p=this.getContentElement("info","txtFooterHeight").getValue()+b.outline.pageUnit;a.border=!1;a.orientation=c;a.width=f;a.height=e;a.marginLeft=d;a.marginRight=g;a.marginTop=k;a.marginBottom=l;a.pageHeader.height=n;a.pageFooter.height=p;h.plugins.pagination.updatePageStyle(h);h.fire("zoom",{type:h.ui.zoomType,ratio:h.ui.zoomRatio,
updateScrollbarVisibility:1})}}})})();